# Generated by Django 3.1.4 on 2022-03-29 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0004_auto_20220329_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='soft_delete',
            field=models.BooleanField(default=False),
        ),
    ]
