# Generated by Django 3.1.4 on 2022-03-29 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0005_post_soft_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
